In [1]:
import numpy as np

numpy 的核心是ndarry,不用于python的array

In [3]:
# 一维数组
arr1=np.array([1,2,3,4])
# 二维数组
arr2=np.array([[1,2,3,4],[5,6,7,8]])
# 创建二维数组但是传一维数据
arr3=np.array([1,2,3,4],ndmin=2)
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]


In [6]:
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)

2
(4,)
(2, 4)
4
8
int64
8


In [7]:
# 修改数组形状
arr2.shape=4,2
print(arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 创建特殊数组

In [14]:
# 等差数组
arr4=np.arange(0,5,1)
print(arr4)
arr5=np.arange(8,1,-1)
print(arr5)

[0 1 2 3 4]
[8 7 6 5 4 3 2]


In [17]:
# 全零数组
arr6 = np.zeros(10)
print(arr6)
# 全一数组
arr7 = np.ones(8)
print(arr7)
# 经常用到的方法 快速生成二维全是1的数组
arr8 = np.ones(12).reshape(3,4)
print(arr8)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 随机数模块

* 种子固定输出结果-ipython中固定一个文本框的结果，py中固定一个py文件的结果

In [29]:
np.random.seed(100)

* 标准正态分布的数据 -均值为0，标准差为1

In [32]:
# 3行3列
# np.random.seed(100)
data1 = np.random.randn(3,3)
print(data1)

[[-0.43813562 -1.11831825  1.61898166]
 [ 1.54160517 -0.25187914 -0.84243574]
 [ 0.18451869  0.9370822   0.73100034]]


* 随机整数

In [36]:
# 1-100以内，生成3行5列随机整数 
np.random.seed(100)
data2 = np.random.randint(1,100,[3,5])
print(data2)

[[ 9 25 68 88 80]
 [49 11 95 53 99]
 [54 67 99 15 35]]


* 0-1范围内的随机实数

In [38]:
# 10 个 0-1范围内的随机实数
data3=np.random.random(10).reshape(2,5)
print(data3)

[[0.10837689 0.21969749 0.97862378 0.81168315 0.17194101]
 [0.81622475 0.27407375 0.43170418 0.94002982 0.81764938]]


# 利用numpy进行统计分析

* 一维数组

In [39]:
arr01 = np.arange(10)
print(arr01)
print(arr01[-1])
print(arr01[3:6])  # 左开右闭
print(arr01[8:2:-2])  # 左开右闭 8 6 4 
# 数组切片修改
arr01[2:4]=10,11
print(arr01)

[0 1 2 3 4 5 6 7 8 9]
9
[3 4 5]
[8 6 4]
[ 0  1 10 11  4  5  6  7  8  9]


* 二维数组

In [51]:
arr02 = np.arange(12).reshape(3,4)
print(arr02)
# 对于行和列都有要求
print(arr02[0:2,1:3])
print(arr02[1,1:3]) # [5,6]
# 选择行
print(arr02[0:2]) # 第1，2行
print(arr02[0]) # 第1行
# 选择列
print(arr02[:,1:3]) # 第2，3列
print(arr02[:,3])# 第4列 
# 一个值
print(arr02[1,2]) # 6
print(arr02[1][2]) # 6

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]
[5 6]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[ 3  7 11]
6
6


# 使用numpy进行文件读写

* 存储 -numpy.savez('xxx',arr1,arr2) 不需要写后缀

    如果存一个数组，生成npy文件，
    
    存两个数组，生成npz文件

In [58]:
# 保存一个数组
arr01 = np.arange(100).reshape(10,10)
np.save('arr01',arr01)
# 保存两个数组
arr02 = np.random.randn(3,5)
np.savez('arr02',arr01,arr02)

* 载入 -numpy.load('xxx.npy|xxx.npz') 一定要写后缀

In [56]:
# 读取npy文件
load_data1 = np.load('arr01.npy')
print(load_data1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [62]:
# 读取npz文件
load_data2 = np.load('arr02.npz')
# 先知道名字再读取
print(load_data2.files)
arr_data1=load_data2['arr_0']
arr_data2=load_data2['arr_1']
print(arr_data1)
print(arr_data2)

['arr_0', 'arr_1']
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[-1.0075773  -0.50873443  0.78148842 -0.65438103  0.04117247]
 [-0.20191691 -0.87081315  0.22893207 -0.40803994 -0.10392514]
 [ 1.56717879  0.49702472  1.15587233  1.83861168  1.53572662]]


# 国民经济核算数据读取

In [69]:
economical_data = np.load('国民经济核算季度数据.npz',allow_pickle=True)
print(economical_data.files)

['columns', 'values']


In [71]:
columns = economical_data['columns']
values = economical_data['values']
print(columns)
print(values)

['序号' '时间' '国内生产总值_当季值(亿元)' '第一产业增加值_当季值(亿元)' '第二产业增加值_当季值(亿元)'
 '第三产业增加值_当季值(亿元)' '农林牧渔业增加值_当季值(亿元)' '工业增加值_当季值(亿元)' '建筑业增加值_当季值(亿元)'
 '批发和零售业增加值_当季值(亿元)' '交通运输、仓储和邮政业增加值_当季值(亿元)' '住宿和餐饮业增加值_当季值(亿元)'
 '金融业增加值_当季值(亿元)' '房地产业增加值_当季值(亿元)' '其他行业增加值_当季值(亿元)']
[[1 '2000年第一季度' 21329.9 ... 1235.9 933.7 3586.1]
 [2 '2000年第二季度' 24043.4 ... 1124.0 904.7 3464.9]
 [3 '2000年第三季度' 25712.5 ... 1170.4 1070.9 3518.2]
 ...
 [67 '2016年第三季度' 190529.5 ... 15472.5 12164.1 37964.1]
 [68 '2016年第四季度' 211281.3 ... 15548.7 13214.9 39848.4]
 [69 '2017年第一季度' 180682.7 ... 17213.5 12393.4 42443.1]]


# 简单统计

* 排序

In [78]:
arr03 = np.random.randint(1,100,[10,10])
print(arr03)
arr03.sort(axis=0)# 按照列递增
print(arr03)
arr03.sort(axis=1)# 按照行递增
print(arr03)

[[41 25 94 59 29 83 83  8 95  3]
 [64  3 88 18 91 94 97 75 54 31]
 [68 29 38 83 18 11 14 82 26 67]
 [16 12 39 23 56 58 88 52 49 54]
 [18 66 43 94 45 17 52 55 56 84]
 [43 62 38 81  3 63 82 17 71 54]
 [99 97 48 49 10 50 54 35  4 12]
 [50 30 37 94 68 27 53 37 74 32]
 [86 93 69 84 72 62 94 37 43 14]
 [49 83 33 39 41 54 94 15 39 87]]
[[16  3 33 18  3 11 14  8  4  3]
 [18 12 37 23 10 17 52 15 26 12]
 [41 25 38 39 18 27 53 17 39 14]
 [43 29 38 49 29 50 54 35 43 31]
 [49 30 39 59 41 54 82 37 49 32]
 [50 62 43 81 45 58 83 37 54 54]
 [64 66 48 83 56 62 88 52 56 54]
 [68 83 69 84 68 63 94 55 71 67]
 [86 93 88 94 72 83 94 75 74 84]
 [99 97 94 94 91 94 97 82 95 87]]
[[ 3  3  3  4  8 11 14 16 18 33]
 [10 12 12 15 17 18 23 26 37 52]
 [14 17 18 25 27 38 39 39 41 53]
 [29 29 31 35 38 43 43 49 50 54]
 [30 32 37 39 41 49 49 54 59 82]
 [37 43 45 50 54 54 58 62 81 83]
 [48 52 54 56 56 62 64 66 83 88]
 [55 63 67 68 68 69 71 83 84 94]
 [72 74 75 83 84 86 88 93 94 94]
 [82 87 91 94 94 94 95 97 97 99]]


* 其他 sum mean std标准差 var方差 min max argmin最小值索引 argmax cumsum累加 aumprod累积

In [84]:
arr03 = np.random.randint(1,100,[10,10])
print(arr03)
# 标准差
print(arr03.std(axis=0))
print(arr03.std(axis=1))
# 累加
print(np.cumsum(arr03,axis=0))

[[85 79  3 88 22 33 81 65 79 18]
 [50 18 53  5 32 50 26 62 81  2]
 [14 24 34 10 36 70 85 55 81 28]
 [68 38 33 47 81  5  5 27 61 60]
 [91 69 24 45 25 75 32 77 91 67]
 [79 79 34 72 18 61 57 90 61 13]
 [16 26 26  8 47 23 55 62 30 77]
 [10 66 11 78  8 39 57 30 66 80]
 [26 76 95 32 85 83  9 41 29 57]
 [53 26  9 75  9 29 35 74 25 99]]
[29.49847454 24.4354251  25.15869631 29.87306479 25.91543941 23.95328787
 26.08371139 19.40128862 23.07899478 31.06267857]
[30.92264542 24.29588443 25.92701294 24.42232585 24.6868386  25.0926284
 21.01903899 27.10811687 28.3867927  28.99034322]
[[ 85  79   3  88  22  33  81  65  79  18]
 [135  97  56  93  54  83 107 127 160  20]
 [149 121  90 103  90 153 192 182 241  48]
 [217 159 123 150 171 158 197 209 302 108]
 [308 228 147 195 196 233 229 286 393 175]
 [387 307 181 267 214 294 286 376 454 188]
 [403 333 207 275 261 317 341 438 484 265]
 [413 399 218 353 269 356 398 468 550 345]
 [439 475 313 385 354 439 407 509 579 402]
 [492 501 322 460 363 468 442 583 604