In [1]:
import numpy as np

In [3]:
# 一维数组
arr1=np.array([1,2,3,4])
# 二维数组
arr2=np.array([[1,2,3,4],[5,6,7,8]])
# 创建二维数组但是传一维数据
arr3=np.array([1,2,3,4],ndmin=2)
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]


In [6]:
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)

2
(4,)
(2, 4)
4
8
int64
8


In [7]:
# 修改数组形状
arr2.shape=4,2
print(arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 创建特殊数组

In [14]:
# 等差数组
arr4=np.arange(0,5,1)
print(arr4)
arr5=np.arange(8,1,-1)
print(arr5)

[0 1 2 3 4]
[8 7 6 5 4 3 2]


In [17]:
# 全零数组
arr6 = np.zeros(10)
print(arr6)
# 全一数组
arr7 = np.ones(8)
print(arr7)
# 经常用到的方法 快速生成二维全是1的数组
arr8 = np.ones(12).reshape(3,4)
print(arr8)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 随机数模块

* 种子固定输出结果-ipython中固定一个文本框的结果，py中固定一个py文件的结果

In [29]:
np.random.seed(100)

* 标准正态分布的数据 -均值为0，标准差为1

In [32]:
# 3行3列
# np.random.seed(100)
data1 = np.random.randn(3,3)
print(data1)

[[-0.43813562 -1.11831825  1.61898166]
 [ 1.54160517 -0.25187914 -0.84243574]
 [ 0.18451869  0.9370822   0.73100034]]


* 随机整数

In [36]:
# 1-100以内，生成3行5列随机整数 
np.random.seed(100)
data2 = np.random.randint(1,100,[3,5])
print(data2)

[[ 9 25 68 88 80]
 [49 11 95 53 99]
 [54 67 99 15 35]]


* 0-1范围内的随机实数

In [38]:
# 10 个 0-1范围内的随机实数
data3=np.random.random(10).reshape(2,5)
print(data3)

[[0.10837689 0.21969749 0.97862378 0.81168315 0.17194101]
 [0.81622475 0.27407375 0.43170418 0.94002982 0.81764938]]


# 利用numpy进行统计分析

* 一维数组

In [39]:
arr01 = np.arange(10)
print(arr01)
print(arr01[-1])
print(arr01[3:6])  # 左开右闭
print(arr01[8:2:-2])  # 左开右闭 8 6 4 
# 数组切片修改
arr01[2:4]=10,11
print(arr01)

[0 1 2 3 4 5 6 7 8 9]
9
[3 4 5]
[8 6 4]
[ 0  1 10 11  4  5  6  7  8  9]


* 二维数组

In [51]:
arr02 = np.arange(12).reshape(3,4)
print(arr02)
# 对于行和列都有要求
print(arr02[0:2,1:3])
print(arr02[1,1:3]) # [5,6]
# 选择行
print(arr02[0:2]) # 第1，2行
print(arr02[0]) # 第1行
# 选择列
print(arr02[:,1:3]) # 第2，3列
print(arr02[:,3])# 第4列 
# 一个值
print(arr02[1,2]) # 6
print(arr02[1][2]) # 6

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]
[5 6]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[ 3  7 11]
6
6
